Add German PDF and Fix print German
bombmanual/bombmanual.github.io pull request #21
Opened 2017-10-29 19:03 UTC by Hexaflexagon

2017-10-29 19:11 UTC, Hexaflexagon commented
I add a geerman PDF file and change the cable translation

2017-10-30 09:33 UTC, brugnara commented
@reneroth & @FroznMine could you please check this PR as I don't speak German? 👀 Many thanks 👍  

Also, thanks in advice for your effort, @Hexaflexagon

2017-10-30 10:13 UTC, FroznMine commented
Looks good to me. Thanks for finding these errors!

2017-10-30 10:48 UTC, reneroth commented on german/index.html
> +			<li>Wählen Sie die durchzuschneidenden Kabel anhand der folgenden Tabelle aus. Ist das auf dem Modul zusehende Kabel mit dem in der Tabelle angegebenen Buchstaben verbunden, so schneiden Sie das K
zusehende - zu sehende

2017-10-30 10:48 UTC, reneroth commented
caught a tiny typo :) thanks for adding a PDF!

2017-11-29 18:49 UTC, Intruder66 commented
At least we have a PDF (and thus a usable printable version), but the margins are pretty big (or the scaling is too low). Maybe you can reduce them?

2017-12-12 14:10 UTC, brugnara commented
the typo @reneroth found is fixed? Just to not do a commit for a missing space :)

2018-01-09 11:42 UTC, brugnara commented
ping

2018-01-09 18:10 UTC, dakira commented
@brugnara the typo is not fixed, yet. @Hexaflexagon

2018-01-09 18:12 UTC, dakira requested changes
looks good to me, except for the typo @reneroth already found

2018-02-15 14:17 UTC, closed without merging